import{initializeApp}from'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';import{getFirestore,collection,doc,onSnapshot,query,where,setDoc,writeBatch,serverTimestamp}from'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
const CFG={apiKey:'AIzaSyCBUb2FqVQouIgyWERxkNsRyRPT5BnsFvo',authDomain:'yokomochi-2d1ad.firebaseapp.com',projectId:'yokomochi-2d1ad',storageBucket:'yokomochi-2d1ad.firebasestorage.app',messagingSenderId:'527899321727',appId:'1:527899321727:web:6a00904d7197dabb47e64a'},BASE=['午前①便 9:30～','午前②便 11:00～','午後③便 14:30～','午後④便 16:30～'],PASS_HASH='24ff5fc43fb72c7eb8df22eaae128989e27a86361d41b7dc8c1c3a5ef040d3a1',DEFAULT_HELP=`【ご利用方法】

1. 空き枠をクリックして配車予定を登録してください。登録済みの予定をクリックすると、内容の修正・削除ができます。

2. 予約不可（赤塗りつぶし）にしたい場合は、便登録の際に「予約不可」のチェックを入れてください。

3. 基本便（午前①便・午前②便・午後③便・午後④便）以外の増便・臨時便は、「＋便追加」ボタンから追加してください。

4. 追加した便の列を削除する場合は、「＋便追加」ボタンを押し、表示される追加便一覧から削除してください。

5. 更新・削除の際は、変更担当者を入力してください。変更内容は「変更履歴」ボタンから確認できます。`,db=getFirestore(initializeApp(CFG));let w=sow(new Date),slots=[...BASE],rows=[],edit=null,help=DEFAULT_HELP,u1,u2,u3;const $=x=>document.querySelector(x);function sow(d){d=new Date(d);d.setHours(12,0,0,0);let n=d.getDay()||7;d.setDate(d.getDate()-n+1);return d}function at(i){let d=new Date(w);d.setDate(d.getDate()+i);return d}function iso(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}function jp(d){return`${d.getMonth()+1}月${d.getDate()}日`}function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}async function hash(s){let b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function load(){u1?.();u2?.();let id=iso(w);u1=onSnapshot(query(collection(db,'schedules'),where('weekStart','==',id)),s=>{rows=s.docs.map(x=>({id:x.id,...x.data()}));render()});u2=onSnapshot(doc(db,'weekConfigs',id),s=>{slots=s.exists()?s.data().slots:[...BASE];BASE.forEach(b=>{if(!slots.includes(b))slots.push(b)});render()});if(!u3)u3=onSnapshot(doc(db,'settings','help'),s=>{help=s.exists()&&s.data().text?s.data().text:DEFAULT_HELP;$('#helpText').textContent=help})}function render(){let end=at(5);$('#range').textContent=`${w.getFullYear()}年 ${jp(w)}～${jp(end)}`;$('#sub').textContent=`${jp(w)}（月）～${jp(end)}（土）`;$('#slot').innerHTML=slots.map(s=>`<option>${esc(s)}</option>`).join('');let h='<div class="cell head">日付</div>'+slots.map(s=>`<div class="cell head">${esc(s)}</div>`).join('');for(let i=0;i<6;i++){let d=at(i),ds=iso(d);h+=`<div class="cell day">${jp(d)}<br>（${'月火水木金土'[i]}）</div>`;for(let s of slots){let r=rows.find(x=>x.date===ds&&x.slot===s);h+=`<div class="cell entry ${r?'':'empty'} ${r?.closed?'closed':''}" data-id="${r?.id||''}" data-date="${ds}" data-slot="${esc(s)}">${r?`<div class="route">${esc(r.route)}</div><div class="meta">担当：${esc(r.driver)}　<span class="pl">${esc(r.pl||'')}</span></div><div class="note">${esc(r.note||'')}</div>`:'クリックして登録'}</div>`}}$('#grid').style.gridTemplateColumns=`110px repeat(${slots.length},minmax(160px,1fr))`;$('#grid').innerHTML=h}
function open(c){edit=rows.find(x=>x.id===c.dataset.id)||null;['date','slot','route','driver','pl','note'].forEach(k=>$('#'+k).value=edit?.[k]||c.dataset[k]||'');$('#closed').checked=!!edit?.closed;$('#who').value='';$('#who').required=!!edit;$('#whoMark').hidden=!edit;$('#del').hidden=!edit;$('#edit').showModal()}$('#grid').onclick=e=>{let c=e.target.closest('.entry');if(c)open(c)};document.querySelectorAll('.cancel').forEach(b=>b.onclick=()=>b.closest('dialog').close());function snap(r){return r?{date:r.date,slot:r.slot,route:r.route||'',driver:r.driver||'',pl:r.pl||'',note:r.note||'',closed:!!r.closed,weekStart:r.weekStart}:null}function hist(op,b,a,who,id){let x=a||b;return{operation:op,scheduleId:id,weekStart:x.weekStart,date:x.date,slot:x.slot,changedBy:who||x.driver,before:snap(b),after:snap(a),createdAt:serverTimestamp()}}
$('#editForm').onsubmit=async e=>{e.preventDefault();let who=$('#who').value.trim();if(edit&&!who)return alert('更新時は変更担当者が必須です。');let d={date:$('#date').value,slot:$('#slot').value,route:$('#route').value.trim(),driver:$('#driver').value.trim(),pl:$('#pl').value.trim(),note:$('#note').value.trim(),closed:$('#closed').checked,weekStart:iso(sow(new Date($('#date').value+'T12:00'))),updatedAt:serverTimestamp()},id=edit?.id||`${d.date}_${encodeURIComponent(d.slot)}`,b=writeBatch(db);b.set(doc(db,'schedules',id),d);b.set(doc(collection(db,'histories')),hist(edit?'更新':'新規',edit,d,who||d.driver,id));await b.commit();$('#edit').close()};$('#del').onclick=async()=>{let who=$('#who').value.trim();if(!who)return alert('削除時は変更担当者が必須です。');if(!confirm('削除しますか？'))return;let b=writeBatch(db);b.set(doc(collection(db,'histories')),hist('削除',edit,null,who,edit.id));b.delete(doc(db,'schedules',edit.id));await b.commit();$('#edit').close()};
$('#addSlot').onclick=()=>{$('#slotPos').innerHTML=['先頭',...slots.map((s,i)=>`${i+1}列目「${s}」の後`)].map((x,i)=>`<option value="${i}">${esc(x)}</option>`).join('');$('#slotName').value='';let a=slots.filter(s=>!BASE.includes(s));$('#slotList').innerHTML=a.length?a.map(s=>`<div class="row">${esc(s)}<button type="button" data-name="${esc(s)}">削除</button></div>`).join(''):'<div class="row">追加便なし</div>';$('#slotDlg').showModal()};$('#slotForm').onsubmit=async e=>{e.preventDefault();let n=$('#slotName').value.trim();if(slots.includes(n))return alert('同じ便名があります。');let a=[...slots];a.splice(Number($('#slotPos').value),0,n);await setDoc(doc(db,'weekConfigs',iso(w)),{slots:a,updatedAt:serverTimestamp()});$('#slotDlg').close()};$('#slotList').onclick=async e=>{let b=e.target.closest('button');if(!b)return;let n=b.dataset.name;if(rows.some(r=>r.slot===n))return alert('登録データがある便は削除できません。');await setDoc(doc(db,'weekConfigs',iso(w)),{slots:slots.filter(s=>s!==n),updatedAt:serverTimestamp()});$('#slotDlg').close()};
$('#helpBtn').onclick=()=>{$('#helpText').textContent=help;$('#helpDlg').showModal()};$('#helpClose').onclick=()=>$('#helpDlg').close();$('#helpEdit').onclick=()=>{$('#helpPassword').value='';$('#helpBody').value=help;$('#helpDlg').close();$('#helpEditDlg').showModal()};$('#helpForm').onsubmit=async e=>{e.preventDefault();if(await hash($('#helpPassword').value)!==PASS_HASH)return alert('パスワードが違います。');await setDoc(doc(db,'settings','help'),{text:$('#helpBody').value.trim(),updatedAt:serverTimestamp()});$('#helpEditDlg').close();alert('利用方法を更新しました。')};
$('#history').onclick=()=>{$('#histList').innerHTML='読込中';$('#histDlg').showModal();onSnapshot(query(collection(db,'histories'),where('weekStart','==',iso(w))),s=>{let a=s.docs.map(x=>x.data()).sort((x,y)=>(y.createdAt?.seconds||0)-(x.createdAt?.seconds||0));$('#histList').innerHTML=a.length?a.map(h=>`<div class="row"><b>${esc(h.operation)}</b>　変更担当者：${esc(h.changedBy||'')}<br>${esc(h.date)} ${esc(h.slot)}<div class="diff">変更前：${esc(JSON.stringify(h.before))}\n変更後：${esc(JSON.stringify(h.after))}</div></div>`).join(''):'履歴なし'})};$('#prev').onclick=()=>{w.setDate(w.getDate()-7);load()};$('#next').onclick=()=>{w.setDate(w.getDate()+7);load()};$('#today').onclick=()=>{w=sow(new Date);load()};$('#pdf').onclick=()=>print();load();
