import './style.css';
import { initializeApp } from 'firebase/app';
import { getFirestore, collection, doc, setDoc, deleteDoc, onSnapshot, query, where } from 'firebase/firestore';
import { firebaseConfig } from './firebase-config.js';

const SLOTS=['午前①便 9:30～','増便① 9:20～','午前②便 11:00～','増便② 11:00～','午後③便 14:30～','増便③ 15:30～','午後④便 16:30～','増便④ 16:30～'];
const DAY_NAMES=['月','火','水','木','金','土'];
let weekStart=startOfWeek(new Date()), records=[], editing=null, unsubscribe=null;
const configured=!Object.values(firebaseConfig).some(v=>String(v).includes('YOUR_'));
let db=null;
if(configured){db=getFirestore(initializeApp(firebaseConfig));}

const app=document.querySelector('#app');
app.innerHTML=`<header class="top"><div><h1>横持便 週間予定表</h1><p>山陽自動車運送往復便</p></div><div class="top-actions"><span id="sync" class="sync">接続確認中</span><button class="btn primary" id="add">＋予定登録</button></div></header><main class="container"><section class="toolbar"><button class="btn" id="prev">‹ 前週</button><button class="btn" id="current">今週</button><button class="btn" id="next">次週 ›</button><strong id="range"></strong><button class="btn" id="pdf">PDF出力</button></section><div id="configError" class="error"></div><p class="notice">表の枠をクリックすると登録・編集できます。PDF出力では、現在表示している週の全予定をA3横帳票として印刷します。</p><section class="board"><div class="sheet"><div class="sheet-title">山陽自動車運送往復便　予定表</div><div class="sheet-range" id="sheetRange"></div><div class="grid" id="grid"></div></div></section><div class="summary" id="summary"></div></main><dialog id="modal" class="modal"><form id="form" class="form"><h2>配車予定</h2><div class="form-grid"><label>日付<input id="date" type="date" required></label><label>便<select id="slot" required>${SLOTS.map(s=>`<option>${s}</option>`).join('')}</select></label><label class="wide">行き先・ルート<input id="route" required placeholder="例：大阪⇒江見⇒山陽"></label><label>担当者<input id="driver" placeholder="例：山野"></label><label>PL数・枚数<input id="pl" placeholder="例：12PL / 空パレット180枚"></label><label class="wide">備考<textarea id="note" rows="3" placeholder="返却不可、送り状、製品・半製品など"></textarea></label><label><input id="closed" type="checkbox"> 予約不可枠として赤表示</label></div><div class="form-actions"><button type="button" class="btn danger" id="remove">削除</button><span class="spacer"></span><button type="button" class="btn" id="cancel">キャンセル</button><button class="btn primary" type="submit">保存</button></div></form></dialog>`;
const $=s=>document.querySelector(s);
function startOfWeek(d){const x=new Date(d);x.setHours(12,0,0,0);const n=x.getDay()||7;x.setDate(x.getDate()-n+1);return x}
function dateAt(i){const d=new Date(weekStart);d.setDate(d.getDate()+i);return d}
function iso(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function jp(d){return `${d.getMonth()+1}月${d.getDate()}日`}
function key(date,slot){return `${date}_${SLOTS.indexOf(slot)}`}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function loadWeek(){if(unsubscribe)unsubscribe();if(!configured){records=JSON.parse(localStorage.getItem('yokomochi-demo')||'[]');$('#sync').textContent='ローカルモード';render();return}const q=query(collection(db,'schedules'),where('weekStart','==',iso(weekStart)));unsubscribe=onSnapshot(q,s=>{records=s.docs.map(x=>({id:x.id,...x.data()}));$('#sync').textContent='共有データ同期中';render()},e=>{$('#sync').textContent='接続エラー';showError(`Firestoreに接続できません: ${e.message}`)})}
function render(){const end=dateAt(5);$('#range').textContent=`${weekStart.getFullYear()}年 ${jp(weekStart)} ～ ${jp(end)}`;$('#sheetRange').textContent=`${jp(weekStart)}（月）～ ${jp(end)}（土）`;let html='<div class="cell head">日付</div>'+SLOTS.map(s=>`<div class="cell head">${esc(s)}</div>`).join('');for(let d=0;d<6;d++){const day=dateAt(d),ds=iso(day),today=ds===iso(new Date());html+=`<div class="cell day ${today?'today':''}"><span>${jp(day)}</span><span>（${DAY_NAMES[d]}）</span></div>`;for(const slot of SLOTS){const r=records.find(x=>x.date===ds&&x.slot===slot);html+=`<div class="cell slot ${r?'':'empty'} ${r?.closed?'closed':''}" data-date="${ds}" data-slot="${esc(slot)}" data-id="${r?.id||''}">${r?`<div class="route">${esc(r.route)}</div><div class="driver">担当：${esc(r.driver||'')}</div>${r.pl?`<span class="pl">${esc(r.pl)}</span>`:''}${r.note?`<div class="note">＊備考＊<br>${esc(r.note)}</div>`:''}`:''}</div>`}}$('#grid').innerHTML=html;const active=records.filter(r=>!r.closed);$('#summary').innerHTML=`<span>登録便数 <b>${active.length}</b></span><span>予約不可枠 <b>${records.filter(r=>r.closed).length}</b></span>`}
function openEditor(date,slot,id){editing=records.find(r=>r.id===id)||null;$('#date').value=editing?.date||date;$('#slot').value=editing?.slot||slot;$('#route').value=editing?.route||'';$('#driver').value=editing?.driver||'';$('#pl').value=editing?.pl||'';$('#note').value=editing?.note||'';$('#closed').checked=!!editing?.closed;$('#remove').style.visibility=editing?'visible':'hidden';$('#modal').showModal()}
$('#grid').onclick=e=>{const c=e.target.closest('.slot');if(c)openEditor(c.dataset.date,c.dataset.slot,c.dataset.id)};$('#add').onclick=()=>openEditor(iso(new Date()),SLOTS[0],'');$('#cancel').onclick=()=>$('#modal').close();
$('#form').onsubmit=async e=>{e.preventDefault();const data={date:$('#date').value,slot:$('#slot').value,route:$('#route').value.trim(),driver:$('#driver').value.trim(),pl:$('#pl').value.trim(),note:$('#note').value.trim(),closed:$('#closed').checked,weekStart:iso(startOfWeek(new Date($('#date').value+'T12:00:00'))),updatedAt:new Date().toISOString()};const id=editing?.id||key(data.date,data.slot);try{if(configured)await setDoc(doc(db,'schedules',id),data);else{const all=JSON.parse(localStorage.getItem('yokomochi-demo')||'[]').filter(x=>x.id!==id);all.push({id,...data});localStorage.setItem('yokomochi-demo',JSON.stringify(all));records=all;render()}$('#modal').close()}catch(err){alert('保存できませんでした: '+err.message)}};
$('#remove').onclick=async()=>{if(!editing)return;if(!confirm('この予定を削除しますか？'))return;try{if(configured)await deleteDoc(doc(db,'schedules',editing.id));else{records=records.filter(r=>r.id!==editing.id);localStorage.setItem('yokomochi-demo',JSON.stringify(records));render()}$('#modal').close()}catch(err){alert('削除できませんでした: '+err.message)}};
$('#prev').onclick=()=>{weekStart.setDate(weekStart.getDate()-7);loadWeek()};$('#next').onclick=()=>{weekStart.setDate(weekStart.getDate()+7);loadWeek()};$('#current').onclick=()=>{weekStart=startOfWeek(new Date());loadWeek()};$('#pdf').onclick=()=>window.print();
function showError(msg){const e=$('#configError');e.textContent=msg;e.style.display='block'}
if(!configured)showError('Firebase設定が未入力のため、この端末だけのローカルモードです。src/firebase-config.js を設定すると、全員で同じ予定を共有できます。');
loadWeek();
