import{initializeApp,getApps}from'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import{getFirestore,doc,onSnapshot,setDoc,collection,serverTimestamp}from'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
const cfg={apiKey:'AIzaSyCBUb2FqVQouIgyWERxkNsRyRPT5BnsFvo',authDomain:'yokomochi-2d1ad.firebaseapp.com',projectId:'yokomochi-2d1ad',storageBucket:'yokomochi-2d1ad.firebasestorage.app',messagingSenderId:'527899321727',appId:'1:527899321727:web:6a00904d7197dabb47e64a'};
const app=getApps()[0]||initializeApp(cfg),db=getFirestore(app),BASE_SLOTS=['午前①便 9:45～','午前②便 11:00～','午後③便 14:30～','午後④便 16:30～'];
const fixed=[
{name:'株式会社東具 東大阪物流センター',address:'大阪府東大阪市稲田新町2-13-11',tel:'06-4309-9241',note:''},
{name:'株式会社石原物流',address:'大阪府摂津市鶴野3丁目3番24号',tel:'072-667-8798',note:''},
{name:'日建返却センター',address:'大阪府東大阪市本庄中2-4-4',tel:'',note:'大阪センコー運輸 東大阪営業所内'}];
let editable=[{name:'倉庫4',address:'未登録',tel:'',note:''},{name:'倉庫5',address:'未登録',tel:'',note:''}];
const cards=document.querySelector('#warehouseCards');
function renderCards(){cards.innerHTML=[...fixed,...editable].map((x,i)=>`<article class="warehouseCard ${i<3?'fixed':'editable'}"><strong>${safe(x.name)}</strong>${safe(x.address)}${x.tel?`\nTel：${safe(x.tel)}`:''}${x.note?`\n${safe(x.note)}`:''}${i>=3?`<button class="editWarehouse" data-index="${i-3}">編集</button>`:''}</article>`).join('')}
function safe(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
onSnapshot(doc(db,'settings','warehouses'),s=>{if(s.exists()&&Array.isArray(s.data().editable))editable=s.data().editable;renderCards()});
cards.onclick=e=>{const b=e.target.closest('.editWarehouse');if(!b)return;const i=Number(b.dataset.index),x=editable[i];document.querySelector('#warehouseIndex').value=i;document.querySelector('#warehouseTitle').textContent=`倉庫${i+4}の編集`;document.querySelector('#warehouseName').value=x.name||'';document.querySelector('#warehouseAddress').value=x.address==='未登録'?'':x.address||'';document.querySelector('#warehouseTel').value=x.tel||'';document.querySelector('#warehouseNote').value=x.note||'';document.querySelector('#warehouseChangedBy').value='';document.querySelector('#warehouseEditDlg').showModal()};
document.querySelector('#warehouseCancel').onclick=()=>document.querySelector('#warehouseEditDlg').close();
document.querySelector('#warehouseForm').onsubmit=async e=>{e.preventDefault();const i=Number(document.querySelector('#warehouseIndex').value),who=document.querySelector('#warehouseChangedBy').value.trim(),before={...editable[i]},after={name:document.querySelector('#warehouseName').value.trim(),address:document.querySelector('#warehouseAddress').value.trim(),tel:document.querySelector('#warehouseTel').value.trim(),note:document.querySelector('#warehouseNote').value.trim()};if(!who)return alert('変更者を入力してください。');editable[i]=after;await setDoc(doc(db,'settings','warehouses'),{editable,updatedAt:serverTimestamp()},{merge:true});await setDoc(doc(collection(db,'histories')),{operation:'倉庫情報更新',changedBy:who,before,after,createdAt:serverTimestamp(),createdAtClient:new Date().toISOString()});document.querySelector('#warehouseEditDlg').close()};
function patchGrid(){const grid=document.querySelector('#grid');if(!grid)return;const headers=[...grid.querySelectorAll('.head')];headers.forEach(h=>{if(h.textContent.includes('午前①便')&&h.textContent.includes('9:30'))h.textContent=h.textContent.replace('9:30','9:45')});const select=document.querySelector('#slot');if(select)[...select.options].forEach(o=>{if(o.textContent.includes('午前①便')&&o.textContent.includes('9:30')){o.textContent=o.textContent.replace('9:30','9:45')}});const cells=[...grid.children],columnCount=headers.length,dayRows=6;if(!columnCount)return;for(let r=0;r<dayRows;r++){const start=columnCount+(r*(columnCount+1)),dayCells=cells.slice(start,start+columnCount+1),entries=dayCells.slice(1),hasTrip=entries.some(c=>c.classList.contains('entry')&&!c.classList.contains('empty'));dayCells.forEach(c=>c.classList.toggle('no-service-day',!hasTrip))}}
const grid=document.querySelector('#grid');if(grid)new MutationObserver(patchGrid).observe(grid,{childList:true,subtree:true});patchGrid();renderCards();
